---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-creds
  namespace: argocd
spec:
  encryptedData:
    docker-password: AgAg696PtSGqsdjTa7dfFAGCeMrSSwgWR0SV/pFYA/hoU0bRMyS2LG5W8hS99waxqARvpzDrYHv7QkA3bG78QAC6MemNS34IKGC8t6kmHof5PXM1O67ViY2ujt45WG4FfupAmRLyx2jV+EUQ36AQdTOFjs8E4FISVkBgg2veRd62QR9rCL+QOQsKDnqlD6Z3AXI6X2YuVtmFMbkwjkq8DuZmeJxhOparW7khSSeDTYu5wTI1Ef9RwjE0+a7f7E0yjsfbT0VwYNG1f1Htcw1T9qONBxRQLfwfRAF9/IROZDKEDQbz/XfWeRta8KyamQsatVIXZCBlZaGkVHMSDyKdoqc/WExDvs95bBSnSXE3FkigDK92XcADk7OxgRya3dGcmPS7rdS+WNtXYUthvafwypQ5197JCPBPcnN9pJkFZssW4N5YVeccPQ3DvS2EcI6FW3KwKqbVCsYo8tF3m/KXCyt1bswp7eZf/K1MZdVZLWtkq9Ty03rOhQX8Zjdxx3jODqXZYJDpHAA4+eEjFJ5O7YouIZulAcrj/dUAukAJ/kudjUVev5wQBCGult0l6sGjdXK2htcZDdxHjbPXS5SZ38adSF8PoPevK4MG9D30P0RpAMBMRXEMitMenzBQH5/eIkANlaNqCUKUPJifTh3kI4t9l1NoOYX1IXUajiZKsgMU31uuH9vYCeqs61TJ2lZXg1YYZ9HzfV8Em3ZxlhCPUA==
    docker-username: AgCmuJ+QlNorCNLnJT8I/VlGXvr7zUunyhN03DHK6kTRbRti9miULd8f4E9FQ2FPNGJcmiR8Jx7t/d2kwrp477aQhnRY06wnZwb3R6S0f0qEKU5CrWljTjtiY9vmVkNEGd4XcnLU6/3jIAIeS8Fhuvs1T7Jo3jNuCxgFSTLdmXuyhPY/aholGoqZsnEcL2/S2kbgPzLSJ88SiSjRSZTXje8NSFxsth3I8NczV1ascBUIQH2/5MmsLhA5UX0Fp8YLu3zGr+WHVPErgyJYH8u6An+/9O1Lm0Ove8diL3ES2TIuondXHurMmOJhw2GliLhwDEYIe5sNqtA5v5KFEX5JLataFj2y4qbVs8s73WdTCBzPor01/lWsjdslOaesriviKr19Q5UTVdFk8Kv8KX3/8WIvla7jcv7pkvM6hNKd7HhumquEI4iK42kDqn7KUFLGVsM0e+CG5r8K/OPfzmmerMxMphJZsEmJtIF1GDIXC/SZSyEI/f2Ggy4xL7AsNNU6fRQaZVz1CRmVdV4NiaA74ak5L9i10MKw14m2BV4WiqY4wQ/MXZZJpved9BNEpMLhRtHfMaJkV05vG2a8kS5Z2O6ICFy0WmyC8MDTt+jm5vkD7ug7hSA57JZg0xNLgobmizUwIAv0BFr01lzKI3HflhWv1RqWPC3SjrH+n5Nq8LZdY7Bj6eM6xi8wj3PbVSZh7sN+CtqAxzWnADGwg0YkRVs=
  template:
    metadata:
      name: docker-creds
      namespace: argocd
    type: Opaque
