namespace: openkubescope

coreApi:
  replicaCount: 2
  image:
    repository: sajaldhiman1999/kubescope
    tag: core-api-v1

scanner:
  replicaCount: 2
  image:
    repository: sajaldhiman1999/kubescope
    tag: scanner-v1

report:
  replicaCount: 2
  image:
    repository: sajaldhiman1999/kubescope
    tag: report-v1

web:
  replicaCount: 2
  image:
    repository: sajaldhiman1999/kubescope
    tag: web-v1

postgres:
  image: postgres:17-alpine

service:
  type: ClusterIP

ingress:
  enabled: true
  host: localhost