apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring
data:
  fluent.conf: |
   <system>
    log_level trace
   </system>
   <match **>
    @type elasticsearch
    host elasticsearch
    port 9200

    logstash_format true

    include_tag_key true
    reconnect_on_error true
    reload_connections false
    request_timeout 30s
    
    @type parser
    key_name log
    reserve_data true
    emit_invalid_record_to_error false
    <parse>

    suppress_type_name true
    </match>
