apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: monitoring

data:
  app-json.conf: |
    <filter kubernetes.**>
      @type dedot
      de_dot_separator _
      de_dot_nested true
    </filter>

    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      emit_invalid_record_to_error false
      hash_value_field app
      <parse>
        @type json
      </parse>
    </filter>