// Demo data for KubeScope demo mode
export const isDemoMode = (searchParams: URLSearchParams | { demo?: string }) => {
  if (searchParams instanceof URLSearchParams) {
    return searchParams.get('demo') === 'true'
  }
  return searchParams.demo === 'true'
}

export const demoMetrics = {
  totalSubjects: 247,
  totalRoles: 89,
  totalBindings: 156,
  criticalRisks: 12,
  highRisks: 28,
  mediumRisks: 45,
  lowRisks: 67,
  lastScanDate: new Date().toISOString(),
}

export const demoScans = [
  {
    id: 'scan-demo-1',
    workspace_id: 'demo-workspace',
    filename: 'production-cluster-rbac.json',
    scan_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    subjects_count: 247,
    roles_count: 89,
    bindings_count: 156,
  },
  {
    id: 'scan-demo-2',
    workspace_id: 'demo-workspace',
    filename: 'staging-cluster-rbac.json',
    scan_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    subjects_count: 183,
    roles_count: 67,
    bindings_count: 124,
  },
  {
    id: 'scan-demo-3',
    workspace_id: 'demo-workspace',
    filename: 'dev-cluster-rbac.json',
    scan_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'completed',
    subjects_count: 145,
    roles_count: 54,
    bindings_count: 98,
  },
]

export const demoRBACData = [
  {
    subject: 'system:serviceaccount:kube-system:admin-user',
    namespace: 'kube-system',
    resource: '*',
    verb: '*',
    role: 'cluster-admin',
    severity: 'critical',
  },
  {
    subject: 'system:serviceaccount:default:deploy-bot',
    namespace: 'default',
    resource: 'secrets',
    verb: 'get,list,watch',
    role: 'secret-reader',
    severity: 'high',
  },
  {
    subject: 'user:john@company.com',
    namespace: '*',
    resource: 'pods',
    verb: 'get,list,create,delete',
    role: 'pod-manager',
    severity: 'medium',
  },
  {
    subject: 'system:serviceaccount:monitoring:prometheus',
    namespace: '*',
    resource: 'nodes,pods,services',
    verb: 'get,list,watch',
    role: 'metrics-reader',
    severity: 'low',
  },
  {
    subject: 'user:sarah@company.com',
    namespace: 'production',
    resource: 'deployments',
    verb: 'get,list,update',
    role: 'deployment-manager',
    severity: 'medium',
  },
  {
    subject: 'system:serviceaccount:ci-cd:gitlab-runner',
    namespace: '*',
    resource: 'pods/exec',
    verb: 'create',
    role: 'pod-executor',
    severity: 'critical',
  },
  {
    subject: 'user:mike@company.com',
    namespace: 'staging',
    resource: '*',
    verb: '*',
    role: 'namespace-admin',
    severity: 'high',
  },
  {
    subject: 'system:serviceaccount:logging:fluentd',
    namespace: '*',
    resource: 'pods/log',
    verb: 'get',
    role: 'log-reader',
    severity: 'low',
  },
]

export const demoFindings = [
  {
    id: 'RBAC-001',
    severity: 'critical',
    category: 'OVERLY_PERMISSIVE',
    title: 'Cluster Admin Access Detected',
    description: 'Service account has full cluster-admin permissions with wildcard access to all resources. This grants unlimited control over the entire cluster.',
    subject: 'admin-user',
    subjectType: 'ServiceAccount',
    namespace: 'kube-system',
    role: 'cluster-admin',
    remediation: 'Replace cluster-admin with a custom role that grants only the minimum required permissions. Use namespace-scoped roles where possible.',
    discoveredAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    impactedSubjects: ['system:serviceaccount:kube-system:admin-user'],
    affectedResources: ['*'],
    cveId: undefined,
  },
  {
    id: 'RBAC-002',
    severity: 'critical',
    category: 'PRIVILEGE_ESCALATION',
    title: 'Pod Exec Permission Detected',
    description: 'Subject can execute arbitrary commands inside running pods, which may lead to container escape and node compromise.',
    subject: 'gitlab-runner',
    subjectType: 'ServiceAccount',
    namespace: 'ci-cd',
    role: 'pod-executor',
    remediation: 'Remove pods/exec permission and use dedicated debugging containers or ephemeral containers instead. Implement pod security policies.',
    discoveredAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    impactedSubjects: ['system:serviceaccount:ci-cd:gitlab-runner'],
    affectedResources: ['pods/exec'],
    cveId: undefined,
  },
  {
    id: 'RBAC-003',
    severity: 'high',
    category: 'OVERLY_PERMISSIVE',
    title: 'Broad Secrets Read Access',
    description: 'Service account has permission to read secrets across multiple namespaces, potentially exposing sensitive credentials and API keys.',
    subject: 'deploy-bot',
    subjectType: 'ServiceAccount',
    namespace: 'default',
    role: 'secret-reader',
    remediation: 'Restrict secrets access to specific secret names or use external secret management solutions like HashiCorp Vault or AWS Secrets Manager.',
    discoveredAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    impactedSubjects: ['system:serviceaccount:default:deploy-bot'],
    affectedResources: ['secrets'],
    cveId: undefined,
  },
  {
    id: 'RBAC-004',
    severity: 'high',
    category: 'OVERLY_PERMISSIVE',
    title: 'Namespace Admin Access',
    description: 'User has full administrative permissions within a namespace, including ability to create privileged pods and modify security policies.',
    subject: 'mike@company.com',
    subjectType: 'User',
    namespace: 'staging',
    role: 'namespace-admin',
    remediation: 'Split namespace-admin role into more granular roles for specific operations (deployments, services, configmaps) without wildcard permissions.',
    discoveredAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    impactedSubjects: ['user:mike@company.com'],
    affectedResources: ['*'],
    cveId: undefined,
  },
  {
    id: 'RBAC-005',
    severity: 'medium',
    category: 'MISCONFIGURATION',
    title: 'Wildcard Resource Access',
    description: 'Role grants access to all resources with limited verbs. While read-only, this provides unnecessary visibility into cluster internals.',
    subject: 'john@company.com',
    subjectType: 'User',
    namespace: '*',
    role: 'pod-manager',
    remediation: 'Explicitly list required resources instead of using wildcards. Consider using ResourceQuota and LimitRange to control resource usage.',
    discoveredAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    impactedSubjects: ['user:john@company.com'],
    affectedResources: ['pods', 'deployments', 'services'],
    cveId: undefined,
  },
  {
    id: 'RBAC-006',
    severity: 'medium',
    category: 'BEST_PRACTICE',
    title: 'ClusterRole Binding to Default Service Account',
    description: 'ClusterRole is bound to the default service account, which is automatically assigned to all pods without explicit service account configuration.',
    subject: 'default',
    subjectType: 'ServiceAccount',
    namespace: 'default',
    role: 'view',
    remediation: 'Create dedicated service accounts for workloads and avoid using the default service account. Set automountServiceAccountToken: false where not needed.',
    discoveredAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    impactedSubjects: ['system:serviceaccount:default:default'],
    affectedResources: ['*'],
    cveId: undefined,
  },
  {
    id: 'RBAC-007',
    severity: 'low',
    category: 'BEST_PRACTICE',
    title: 'Anonymous User Access',
    description: 'Anonymous users have limited read access to API server. While low risk, this provides information disclosure.',
    subject: 'system:anonymous',
    subjectType: 'User',
    namespace: '*',
    role: 'system:public-info-viewer',
    remediation: 'Disable anonymous auth if not required: --anonymous-auth=false. Ensure API server is not exposed to public internet.',
    discoveredAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    impactedSubjects: ['system:anonymous'],
    affectedResources: ['healthz', 'version'],
    cveId: undefined,
  },
]

export const demoRiskFindings = demoFindings

export const demoClusters = [
  {
    id: 'cluster-1',
    name: 'production-us-west',
    environment: 'production',
    version: 'v1.28.3',
    nodes: 12,
    status: 'healthy',
    lastSync: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cluster-2',
    name: 'staging-us-east',
    environment: 'staging',
    version: 'v1.28.2',
    nodes: 6,
    status: 'healthy',
    lastSync: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cluster-3',
    name: 'dev-eu-central',
    environment: 'development',
    version: 'v1.29.0',
    nodes: 4,
    status: 'warning',
    lastSync: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
]
