namespace: openkubescope
coreApi:
  replicaCount: 2
  image:
    repository: sajaldhiman1999/kubescope-core-api
    tag: 344f0d3b3da618910ed97b1de66eb06d153c108d
scanner:
  replicaCount: 2
  image:
    repository: sajaldhiman1999/kubescope-rbac-scanner-service
    tag: cf4596b85515cc486670146b5b202e6a8bccaf8d
report:
  replicaCount: 2
  image:
    repository: sajaldhiman1999/kubescope-report-service
    tag: cf4596b85515cc486670146b5b202e6a8bccaf8d
web:
  replicaCount: 2
  image:
    repository: sajaldhiman1999/kubescope-web
    tag: 395c10b97c7f4724bfa9f43dac5d3e6f8a7ad167
postgres:
  image: postgres:17-alpine
service:
  type: ClusterIP
ingress:
  enabled: true
  host: localhost
