apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: openkubescope
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 25Gi
#sajal