---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgAoNQAMbguCd9N7b+G5iTVpxPqkQ9JPTns/GbAZDCCFtSrOf9ZTqLvI1OAcfJ8P3VQUAN9Duwasjp+RySOBOo8KC97HYPf+qKTkGWVfOFchhYZgdo4A0766DwnccqDESy6ABEVCih1/CUmfTpyXyS9K01Gf3kFytYyeLljxOaXr/o1BfYU/IQAJaHi+RpJU+AdXsHULDcJqDHaQmNH+JiEaduOeuCp1VWu06b7Vx5PNZ4f4r5+Q1B7e/HRIbSwvgcYTVUkziMpbngam1RrZ4Cb55k2X8+dlfg53vd2sEzBHtKkXqcYwhYXUIGjuFwJiqIAhgydUAnAFs+Fcgn9ULFZXBo7ozofUyHqJNVnNfKOChxdrDX3S3thJNzRz7Lo7fKUx+QxkdU0a4dDX8NiO1BwxoRGhwOnlK+DJPYFgcfsqZPnFzRZg61QgFV8EjJC7rQwwC7ncsM3KkjPfCfe+/Nu+BGZrXTFrw1t53nYPlJu6nVmklAOZYBisJGBsfdSjIe+lxKIaY1ydIZ05+wCaf8f1OqRbT/Dt+USsSDhEVvA7hHbqt8pJdjD3f5nT3VQqD0V69T7LQILGBRnUUiqaJQ1poR1lH6QOUhhWZgKyGlq5K7Bc/SDML+AINYSKJpiaC/BbfR0tI9ylFcDzq9a7FeWGyeDcjXlErdD1Xm5eXqLZj+6nb3m99IVK9HVNrh85kw92zrYGIFxrF7nFiAeTwlz34xDDdQFKBgk0PY3muGZg4fZka5CLqzDc
    username: AgBsuUxX46SQu5VR+5Si8GSLHuCAhK7jGElHOcx0xEWrQ7VePRplwyP5GOaC9eiw13WqAI/j54F037ItNvSBGYKZiuoLR93Bcz/8KqyL39D8T2MKgsY737O0LqvEwO1+/SOMc7Y/FiqQbgl11NWknV8qaTU0p0e9eGiEHAbgmnZUQ39H4a8mxJcOaGIFWHz8MBpTDfR9CG9xA8x+QUbyk3AeCbid9DkVahhUaVIaP8lKleXcaxHgKXB1tmOHPpFQUodexagvLgkQY5EFDh0vRD08UqAfy3ojzeq3gDXQjZKRxBO1FKCFvLmt4NHthJ2neR5lOQO8bYFcf57AmHfvxZuXFf4P19vxxvh1K1woRGXgl8g8615gOkpdC3Pb1Y4IhX3rnao0qtsV3H+G2Udga8S7NJhbskCDU683Avhy9Yu8tr55WI+Zqf97+i/CT2BaS1U4k7LAnnNCUuJGKaQzkGmYBPTRBqsZ3AQAHjcUMP3R99h70N6v2bpt7pBmBz8b2t1RY4OkCx/6rjvUbO0zqoSfSDf8Mw6DgW8qA5ROpfAogzZ0v2fPZxb0E75k4U4OGbyJ3iq99ddO4tXYSVYfl9JGfH7N0jkhT4M0g8plYOebwnOZOpsi8Qe2jBh53bVRd/uHhlpEHLHKzfOhbaPBqkDwN/qijyQ3XOa9tqQYJr6TWRJpcNIt5xfl1xs7qFcsAUnTAbcbwNT5FQ==
  template:
    metadata:
      name: git-creds
      namespace: argocd
    type: Opaque
