apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: openkubescope
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard