---
name: Infra Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: Action to perform
        required: true
        default: plan
        type: choice
        options:
          - apply
          - destroy
permissions:
  contents: read
  id-token: write
jobs:
  terraform_workflow:
    name: terraform apply
    if: ${{ github.event.inputs.action == 'apply'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup OIDC connection
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: us-east-1
          audience: sts.amazonaws.com
      - name: Verify AWS Connection
        run: aws sts get-caller-identity
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6

      - name: terraform init
        working-directory: ./infra
        run: terraform init
      
      - name: tf lint
        run: |
          curl -L https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        
      - name: initialize tflint
        working-directory: ./infra
        run: tflint --init
      
      - name: Run tflint
        working-directory: ./infra
        run: tflint
     
      - name: Set up Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: 3.9
      - name: Test with Checkov
        id: checkov
        continue-on-error: true
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./infra
          framework: terraform 
          
          output_format: cli,sarif
          output_file_path: console,results.sarif
        

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        if: success() || failure()
        with:
          sarif_file: results.sarif
  
      - name: creating infra 
        working-directory: ./infra
        run: terraform apply --auto-approve
          
  terraform_destory:
    name: terraform_destory
    if: ${{ github.event.inputs.action == 'destory '}}
    runs-on: ubuntu-latest

    steps: 
      - name: destroy infra
        working-directory: ./infra
        run: terraform destory --auto-approve
